routes/route.py
from flask import Blueprint, request, redirect, url_for, render_template, flash, send_from_directory, abort, session
from models.db import db, BlogPost, User, CommentTable
from forms.form import NewPost, NewUser, ExistingUser, Comments
from werkzeug.security import generate_password_hash, check_password_hash
import datetime
from flask_login import login_user, current_user, login_required, logout_user
from functools import wraps

main = Blueprint("main", __name__)

def is_admin(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        if current_user.is_authenticated:  
            id = current_user.id
            
            if id != 1:
                return abort(403)
            return func(*args, **kwargs)
        else:
            return abort(401)
            
    return wrapper


@main.route('/')
def home():
    posts = db.session.execute(db.select(BlogPost)).scalars().all()
    if current_user.is_authenticated:
        return render_template('index.html', all_posts=posts, user_id=current_user.id)
    return render_template("index.html", all_posts=posts, user_id=None)

# TODO: Add a route so that you can click on individual posts.
@main.route('/post/<int:post_id>', methods=["GET", "POST"])
def show_post(post_id):
    # TODO: Retrieve a BlogPost from the database based on the post_id
    
    comments = Comments()
    login_form = ExistingUser()
    if request.method == "POST":
        if not current_user.is_authenticated:
            flash('You are not logged in! Please register or login to write a comment!')
            return redirect('/login')
        new_comment = CommentTable(
            author_id = current_user.id,
            post_id = post_id,
            text = request.form.get('body')
        )
        db.session.add(new_comment)
        db.session.commit()
        return redirect(f'/post/{post_id}')
    requested_post = db.get_or_404(BlogPost, post_id)
    
    return render_template("post.html", post=requested_post, form=comments, user_id=current_user.id or None)


@main.route('/new-post', methods=['GET', 'POST'])
@is_admin
def make_post():
    blog_form = NewPost()
    
    now = datetime.datetime.now()
    x = datetime.datetime(now.year, now.month, now.day)
    month = x.strftime("%B")
    if request.method == "POST":
        new_data = BlogPost(
            title = request.form.get('title'),
            subtitle = request.form.get("subtitle"),
            date = f"{month} {now.day}, {now.year}",
            body = request.form.get('body'), 
            author_id = current_user.id,
            img_url = request.form.get('img_url')
        )
        db.session.add(new_data)
        db.session.commit()
        return redirect('/')
    return render_template("make-post.html", forms=blog_form, user_id=current_user.id or None)
# TODO: edit_post() to change an existing blog post

@main.route('/edit-post/<int:id>', methods=["POST", "GET"])
def edit_post(id):
    data = db.get_or_404(BlogPost, id)
    blog_form = NewPost(
        title  = data.title,
        subtitle = data.subtitle,
        name = data.author,
        img_url =  data.img_url,
        body = data.body
    )
    if request.method == "POST":
        data.title = request.form.get('title')
        data.subtitle = request.form.get('subtitle')
        data.author = request.form.get('name')
        data.img_url = request.form.get('img_url')
        data.body = request.form.get('body')
        db.session.commit()
        return redirect(f'/post/{id}')
    
    
    return render_template("make-post.html", forms=blog_form, is_edit=True)

# TODO: delete_post() to remove a blog post from the database
@main.route("/delete-post/<int:id>")
@is_admin
def delete_post(id):
    data = db.get_or_404(BlogPost, id)
    if data:
        for comment in data.comments:
            db.session.delete(comment)
        db.session.delete(data)
        db.session.commit()
        return redirect('/')
# Below is the code from previous lessons. No changes needed.
@main.route("/about")
def about():
    return render_template("about.html")


@main.route('/contact')
def contact():
    return render_template('contact.html')

@main.route('/register', methods=["GET", "POST"])
def register():
    register_form = NewUser()
    if request.method == "POST":
        new_user = User(
           email = request.form.get('email'),
           password = generate_password_hash(request.form.get('password'), salt_length=6, method='pbkdf2:sha256'),
           name = request.form.get('name') 
        )
        data = db.session.execute(db.select(User).where(User.email == request.form.get('email')))
        data = data.scalar()
        if data:
            flash('This email already signed up, please login!')
            return redirect(url_for('main.login'))
        else:
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user)
            return redirect(url_for('main.home'))
        
    return render_template('register.html', form=register_form)


@main.route('/login', methods=["GET", "POST"])
def login():
    login_form = ExistingUser()
    if request.method == "POST":
        email = request.form.get("email")
        password = request.form.get('password')
        data = db.session.execute(db.select(User).where(User.email == email))
        data = data.scalar()
        if not data:
            flash("This email doesn't exists, please sign up!")
        elif check_password_hash(data.password, password):
            login_user(data)
            return redirect(url_for('main.home'))
        else:
            flash("Password is incorrect, please try again!")
    return render_template('login.html', form=login_form)


@main.route('/logout')
@login_required
def logout():
    logout_user()
    session.clear()
    return redirect(url_for('main.home'))

templates/about.html
{% include "header.html" %}

<!-- Page Header-->
<header
  class="masthead"
  style="background-image: url('../static/assets/img/about-bg.jpg')"
>
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="page-heading">
          <h1>About Me</h1>
          <span class="subheading">This is what I do.</span>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- Main Content-->
<main class="mb-4">
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <p>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe
          nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis
          sit soluta odio, adipisci quas excepturi maxime quae totam ducimus
          consectetur?
        </p>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius
          praesentium recusandae illo eaque architecto error, repellendus iusto
          reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in
          officia voluptas voluptatibus, minus!
        </p>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut
          consequuntur magnam, excepturi aliquid ex itaque esse est vero natus
          quae optio aperiam soluta voluptatibus corporis atque iste neque sit
          tempora!
        </p>
      </div>
    </div>
  </div>
</main>

{% include "footer.html" %}

templates/contact.html
{% include "header.html" %}

<!-- Page Header-->
<header
  class="masthead"
  style="background-image: url('../static/assets/img/contact-bg.jpg')"
>
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="page-heading">
          {% if msg_sent: %}
          <h1>Successfully sent your message</h1>
          {% else: %}
          <h1>Contact Me</h1>
          {% endif %}
          <span class="subheading">Have questions? I have answers.</span>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- Main Content-->
<main class="mb-4">
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <p>
          Want to get in touch? Fill out the form below to send me a message and
          I will get back to you as soon as possible!
        </p>
        <div class="my-5">
          <!-- * * * * * * * * * * * * * * *-->
          <!-- * * Simplified SB Contact Form for the Tutorial* *-->
          <form
            id="contactForm"
            name="sentMessage"
            action="{{ url_for('contact') }}"
            method="post"
          >
            <div class="form-floating">
              <input
                class="form-control"
                id="name"
                name="name"
                type="text"
                placeholder="Enter your name..."
                required
              />
              <label for="name">Name</label>
            </div>
            <div class="form-floating">
              <input
                class="form-control"
                id="email"
                name="email"
                type="email"
                placeholder="Enter your email..."
                required
              />
              <label for="email">Email address</label>
            </div>
            <div class="form-floating">
              <input
                class="form-control"
                id="phone"
                name="phone"
                type="tel"
                placeholder="Enter your phone number..."
                required
              />
              <label for="phone">Phone Number</label>
            </div>
            <div class="form-floating">
              <textarea
                class="form-control"
                id="message"
                name="message"
                placeholder="Enter your message here..."
                required
                style="height: 12rem"
              ></textarea>
              <label for="message">Message</label>
            </div>
            <br />
            <button
              class="btn btn-danger text-uppercase"
              id="submitButton"
              type="submit"
            >
              NOT USED in Day 67
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</main>

{% include "footer.html" %}

templates/footer.html
        <!-- Footer-->
        <footer class="border-top">
          <div class="container px-4 px-lg-5">
              <div class="row gx-4 gx-lg-5 justify-content-center">
                  <div class="col-md-10 col-lg-8 col-xl-7">
                      <ul class="list-inline text-center">
                          <li class="list-inline-item">
                              <a href="#!">
                                  <span class="fa-stack fa-lg">
                                      <i class="fas fa-circle fa-stack-2x"></i>
                                      <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                  </span>
                              </a>
                          </li>
                          <li class="list-inline-item">
                              <a href="#!">
                                  <span class="fa-stack fa-lg">
                                      <i class="fas fa-circle fa-stack-2x"></i>
                                      <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                  </span>
                              </a>
                          </li>
                          <li class="list-inline-item">
                              <a href="#!">
                                  <span class="fa-stack fa-lg">
                                      <i class="fas fa-circle fa-stack-2x"></i>
                                      <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                  </span>
                              </a>
                          </li>
                      </ul>
                      <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2023</div>
                  </div>
              </div>
          </div>
      </footer>
      <!-- Bootstrap core JS-->
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
      <!-- Core theme JS-->
      <script src="{{ url_for('static', filename='js/scripts.js') }}"></script>
  </body>
</html>

templates/header.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Clean Blog - Start Bootstrap Theme</title>
    {% block styles %}
    <!-- Load Bootstrap-Flask CSS here -->
    {{ bootstrap.load_css() }}
    <link
      rel="icon"
      type="image/x-icon"
      href="{{ url_for('static', filename='assets/favicon.ico') }}"
    />
    <!-- Font Awesome icons (free version)-->
    <script
      src="https://use.fontawesome.com/releases/v6.3.0/js/all.js"
      crossorigin="anonymous"
    ></script>
    <!-- Google fonts-->
    <link
      href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"
      rel="stylesheet"
      type="text/css"
    />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link
      href="{{ url_for('static', filename='css/styles.css') }}"
      rel="stylesheet"
    />
    {% endblock %}
  </head>
  <body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
      <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="/">Start Bootstrap</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarResponsive"
          aria-controls="navbarResponsive"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          Menu
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ms-auto py-4 py-lg-0">
            <li class="nav-item">
              <a
                class="nav-link px-lg-3 py-3 py-lg-4"
                href="/"
                >Home</a
              >
            </li>
            {%if user_id%}
              <li class="nav-item">
                <a
                  class="nav-link px-lg-3 py-3 py-lg-4"
                  href="{{ url_for('main.logout') }}"
                  >Log Out</a
                >
              </li>
            {% else %}
              <li class="nav-item">
                <a
                  class="nav-link px-lg-3 py-3 py-lg-4"
                  href="{{ url_for('main.login') }}"
                  >Login</a
                >
              </li>
              <li class="nav-item">
                <a
                  class="nav-link px-lg-3 py-3 py-lg-4"
                  href="{{ url_for('main.register') }}"
                  >Register</a
                >
              </li>
            {% endif %}
            <li class="nav-item">
              <a
                class="nav-link px-lg-3 py-3 py-lg-4"
                href="{{ url_for('main.about') }}"
                >About</a
              >
            </li>
            <li class="nav-item">
              <a
                class="nav-link px-lg-3 py-3 py-lg-4"
                href="{{ url_for('main.contact') }}"
                >Contact</a
              >
            </li>
          </ul>
        </div>
      </div>
    </nav>

templates/index.html
{% include "header.html" %}

<!-- Page Header-->
<header
  class="masthead"
  style="background-image: url('../static/assets/img/home-bg.jpg')"
>
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="site-heading">
          <h1>Clean Blog</h1>
          <span class="subheading">A Blog Theme by Start Bootstrap</span>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- Main Content-->
<div class="container px-4 px-lg-5">
  <div class="row gx-4 gx-lg-5 justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-7">
      <!-- Post preview-->
      {% for post in all_posts %}
      <div class="post-preview">
        <a href="{{ url_for('main.show_post', post_id=post.id) }}">
          <h2 class="post-title">{{ post.title }}</h2>
          <h3 class="post-subtitle">{{ post.subtitle }}</h3>
        </a>
        <!-- TODO: Add code to delete posts below -->
        <p class="post-meta">
          Posted by
          <a href="#">{{post.author.name}}</a>
          on {{post.date}}
          {%if user_id == 1%}
            <a href="{{url_for('main.delete_post', id=post.id)}}">✘</a>
          {%endif%}
        </p>
      </div>
      <!-- Divider-->
      <hr class="my-4" />
      {% endfor %}

      <!-- New Post -->
      {% if user_id == 1 %}
        <div class="d-flex justify-content-end mb-4">
        <!-- TODO: Adding new posts -->
          <a
            class="btn btn-primary float-right"
            href="{{url_for('main.make_post')}}"
            >Create New Post</a
          >
        </div>
      {% endif %}
      <!-- Pager-->
      <!-- <div class="d-flex justify-content-end mb-4">
        <a class="btn btn-secondary text-uppercase" href="#!">Older Posts →</a>
      </div> -->
    </div>
  </div>
</div>

{% include "footer.html" %}

templates/login.html
{% from "bootstrap5/form.html" import render_form %} {% block content %} {%
include "header.html" %}

<!-- Page Header -->
<header
  class="masthead"
  style="background-image: url('../static/assets/img/login-bg.jpg')"
>
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="page-heading">
          <h1>Log In</h1>
          <span class="subheading">Welcome Back!</span>
        </div>
      </div>
    </div>
  </div>
</header>

<main class="mb-4">
  <div class="container">
    <div class="row">
      <!-- TODO: add a flash message here for users registering twice -->
      <div class="col-lg-8 col-md-10 mx-auto">
        {% with messages = get_flashed_messages() %}
          {% if messages %}
            {%for message in messages%}
            <p style="color: red;">{{ message }}</p>
            {%endfor%}
          {%endif%}
        {%endwith%}
        {{render_form(form)}}
        <!--TODO: render login form here-->
      </div>
    </div>
  </div>
</main>

{% include "footer.html" %} {% endblock %}

templates/make-post.html
{% block content %} {% include "header.html" %}
{% from "bootstrap5/form.html" import render_form %}
<!-- Page Header -->
<header
  class="masthead"
  style="background-image: url('../static/assets/img/edit-bg.jpg')"
>
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="page-heading">
          <!-- TODO: Show a different h1 if editing existing post -->
          {% if is_edit %}
            <h1>Edit Post</h1>
          {%else%}
            <h1>New Post</h1>
          {%endif%}
          <span class="subheading"
            >You're going to make a great blog post!</span
          >
        </div>
      </div>
    </div>
  </div>
</header>

<main class="mb-4">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        {{ckeditor.load()}}
        {{ckeditor.config(name='body')}}
        {{render_form(forms, novalidate=True, button_map={"submit": "primary"})}}

      </div>
    </div>
  </div>
</main>
{% include "footer.html" %} {% endblock %}

templates/post.html
{% include "header.html" %}
{%from "bootstrap5/form.html" import render_form%}
<!-- Page Header-->
<header class="masthead" style="background-image: url('{{post.img_url}}')">
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="post-heading">
          <h1>{{ post.title }}</h1>
          <h2 class="subheading">{{ post.subtitle }}</h2>
          <span class="meta"
            >Posted by
            <a href="#">{{ post.author.name }}</a>
            on {{ post.date }}
          </span>
        </div>
      </div>
    </div>
  </div>
</header>

<!-- Post Content -->
<article>
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        {{ post.body|safe }}
        {%if user_id == 1%}
          <div class="d-flex justify-content-end mb-4">
            <!-- TODO: Editing posts-->
            <a
              class="btn btn-primary float-right"
              href="{{url_for('main.edit_post', id=post.id)}}"
              >Edit post
              </a>
          </div>
        {%endif%}

        {{ckeditor.load()}}
        {{ckeditor.config(name='body')}}
        {{render_form(form, novalidate=True, button_map={"submit": "primary"})}}
        
        <div class="comment">
          <ul class="commentList">
            {%for comment in post.comments: %}
              <li>
                <div class="commenterImage">
                  <img src="{{comment.author.email | gravatar}}" alt="img">
                </div>
                <div class="commentText">
                  {{comment.text | safe}}
                  <span class="sub-text">{{comment.author.name}}</span>
                </div>
              </li>
            {%endfor%}
          </ul>
        </div>
      </div>
    </div>
  </div>
</article>

{% include "footer.html" %}

templates/register.html
{% from "bootstrap5/form.html" import render_form %} {% block content %} {%
include "header.html" %}

<!-- Page Header -->
<header
  class="masthead"
  style="background-image: url('../static/assets/img/register-bg.jpg')"
>
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="page-heading">
          <h1>Register</h1>
          <span class="subheading">Start Contributing to the Blog!</span>

        </div>
      </div>
    </div>
  </div>
</header>

<main class="mb-4">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        {{render_form(form)}}

      </div>
    </div>
  </div>
</main>

{% include "footer.html" %} {% endblock %}